{{- /*
This job upgrades the database associated with this service.  It runs:
  * Before the deployment is installed for the first time
  * Before the deployment is updated
  * After the chart is rolled back to a previous version (this brings the database up to date after it has been re-wound to base)
*/ -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "versions_service.fullname" . }}-migrate
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ template "versions_service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
          - configMapRef:
              name: {{ template "versions_service.fullname" . }}-env
          - secretRef:
              name: {{ template "versions_service.fullname" . }}-secrets
          args:
            - /bin/sh
            - -c
            - export FLASK_APP=autoapp.py && flask db upgrade
