{{- /*
This configmap sets all of the newrelic-related environment variables.
*/ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "versions_service.fullname" . }}-newrelic-env
  labels:
{{ include "labels" . | indent 4 }}
data:
  NEW_RELIC_APP_NAME: {{ template "versions_service.fullname" . }}-{{ .Release.Namespace }}
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
  NEW_RELIC_HIGH_SECURITY: "true"
  NEW_RELIC_LOG: stderr
  NEW_RELIC_LOG_LEVEL: info
  NEW_RELIC_STARTUP_TIMEOUT: "10"
  NEW_RELIC_SHUTDOWN_TIMEOUT: "10"
  NEW_RELIC_LABELS: |-
    helm_release:{{ .Release.Name }};
    chart:{{ .Chart.Name }};
    namespace:{{ .Release.Namespace }};
    syEnvironment:{{ .Values.global.environment }};
    team:{{ .Values.global.team }}
