{{- /*
This secrets file basically takes encrypted values and set them at environment variables.
These are then referenced from the deployment.
*/ -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "versions_service.fullname" . }}-secrets
  labels:
{{ include "labels" . | indent 4 }}
type: Opaque
data:
  NEW_RELIC_LICENSE_KEY: "{{ .Values.global.newrelic.key | b64enc }}"
  PGPASSWORD: "{{ .Values.database.password | b64enc }}"
  DATABASE_URI: "{{ printf "postgresql://%s:%s@%s:%s/%s" .Values.database.user .Values.database.password .Values.database.host (.Values.database.port | toString) .Values.database.name | b64enc }}"
  SECRET_KEY: "{{ .Values.app.secret_key }}"
